# Generated by Django 4.1.4 on 2022-12-19 02:13

import art.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to=art.models.id_prefixed_filename)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to=art.models.id_prefixed_filename)),
                ('title', models.CharField(max_length=500)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('acquired', models.CharField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.artist')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.location')),
                ('medium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.medium')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
