# Generated by Django 4.1.4 on 2022-12-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='medium_details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
