# Generated by Django 4.1.4 on 2022-12-24 05:19

import art.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_piece_medium_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='portrait',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=art.models.id_prefixed_filename),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=art.models.id_prefixed_filename),
        ),
    ]
