# Generated by Django 4.1.4 on 2022-12-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_alter_artist_portrait_alter_piece_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='notes_private',
            field=models.TextField(blank=True),
        ),
    ]
