# Generated by Django 4.1.4 on 2022-12-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_piece_notes_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='notes_private',
            field=models.TextField(blank=True, verbose_name='Private notes'),
        ),
    ]
