# Generated by Django 4.1.4 on 2022-12-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_alter_piece_notes_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='tagged',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
