# Generated by Django 4.1.4 on 2022-12-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_piece_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
