# Generated by Django 4.1.4 on 2023-06-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_piece_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
