# Generated by Django 4.1.4 on 2023-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_piece_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.SlugField(max_length=1024, unique=True),
        ),
    ]
