# Generated by Django 6.0.5 on 2026-05-31 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_alter_piece_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.medium'),
        ),
    ]
