# Generated by Django 6.0.5 on 2026-05-31 20:39

import art.models
import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_alter_piece_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=art.models.id_prefixed_filename),
        ),
        migrations.AlterField(
            model_name='piece',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.medium'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
