# Generated by Django 6.0.5 on 2026-05-31 21:33

from django.db import migrations, models


def _dedupe(descriptions):
    """Given descriptions in a stable order, return the new description for each
    so they're all unique. The first occurrence keeps its name; later duplicates
    get the smallest free " <n>" suffix (n >= 2) that collides with neither an
    existing description nor one already assigned in this pass.
    """
    originals = set(descriptions)
    assigned = set()
    result = []
    for desc in descriptions:
        if desc not in assigned:
            assigned.add(desc)
            result.append(desc)
            continue
        n = 2
        while f'{desc} {n}' in originals or f'{desc} {n}' in assigned:
            n += 1
        new = f'{desc} {n}'
        assigned.add(new)
        result.append(new)
    return result


def dedupe_descriptions(apps, schema_editor):
    """Make Medium/Location descriptions unique before the unique constraint is
    applied, so this migration doesn't fail on databases that already contain
    duplicates. Non-destructive: duplicates are renamed, never merged/deleted.
    """
    for model_name in ('Medium', 'Location'):
        model = apps.get_model('art', model_name)
        rows = list(model.objects.order_by('pk'))
        for row, new_description in zip(rows, _dedupe([r.description for r in rows]), strict=True):
            if row.description != new_description:
                row.description = new_description
                row.save(update_fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_alter_piece_image_alter_piece_medium_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_descriptions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
