# Generated by Django 6.0.5 on 2026-05-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_alter_location_description_alter_medium_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
