# Generated by Django 6.0.5 on 2026-06-03 03:19

from django.db import migrations, models


def backfill_image_dimensions(apps, schema_editor):
    """Populate width/height for images uploaded before these columns existed."""
    from django.core.files.storage import default_storage
    from PIL import Image

    Piece = apps.get_model('art', 'Piece')
    for pk, name in Piece.objects.exclude(image='').exclude(image__isnull=True).values_list('pk', 'image'):
        if not name:
            continue
        try:
            with default_storage.open(name) as fh:
                width, height = Image.open(fh).size
        except Exception:
            continue  # missing/unreadable file — leave dimensions null
        Piece.objects.filter(pk=pk).update(image_width=width, image_height=height)


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0015_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_image_dimensions, migrations.RunPython.noop),
    ]
