# Generated by Django 6.0.5 on 2026-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0016_piece_image_height_piece_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='purchase_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('JPY', 'JPY'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('INR', 'INR'), ('NZD', 'NZD'), ('SEK', 'SEK')], default='', max_length=3),
        ),
    ]
