# Generated by Django 6.0.5 on 2026-06-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0017_piece_purchase_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('in', 'in'), ('cm', 'cm')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='piece',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
