# Generated by Django 6.0.5 on 2026-06-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0018_piece_dimension_unit_piece_height_piece_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('JPY', 'JPY'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('INR', 'INR'), ('NZD', 'NZD'), ('SEK', 'SEK')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_dimension_unit',
            field=models.CharField(choices=[('in', 'in'), ('cm', 'cm')], default='in', max_length=2),
        ),
    ]
