# Generated by Django 6.0.5 on 2026-06-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0019_sitesettings_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='art.artist'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='art.location'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='art.medium'),
        ),
    ]
