# Generated by Django 6.0.5 on 2026-06-05 03:05

import art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0022_piecedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecedocument',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, storage=art.models.private_document_storage, upload_to=art.models.piece_document_thumb_path),
        ),
    ]
