# Generated by Django 6.0.5 on 2026-06-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0023_piecedocument_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='public_sort',
            field=models.CharField(choices=[('acquired_desc', 'Date acquired, newest first'), ('acquired_asc', 'Date acquired, oldest first'), ('title', 'Title (A–Z)'), ('artist', 'Artist name (A–Z)')], default='acquired_desc', help_text='Order pieces are listed in on the public “All pieces” page.', max_length=20, verbose_name='Public sort order'),
        ),
    ]
