# Generated by Django 6.0.5 on 2026-06-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0024_sitesettings_public_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='image_lqip',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
