# Generated by Django 6.0.5 on 2026-08-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0025_piece_image_lqip'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
