# Generated by Django 6.0.5 on 2026-08-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0026_piece_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='quick_add_drafts',
            field=models.BooleanField(default=True, help_text='On: captured photos stay off the public site until you fill in their details. Off: they appear in the public gallery straight away, titleless, with a “Not set” artist and location.', verbose_name='Quick add starts pieces as drafts'),
        ),
    ]
