# Generated by Django 6.0.5 on 2026-08-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0027_sitesettings_quick_add_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_placeholder',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_placeholder',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='piece',
            name='slug_settled',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_placeholder', True)), fields=('is_placeholder',), name='unique_placeholder_artist'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_placeholder', True)), fields=('is_placeholder',), name='unique_placeholder_location'),
        ),
    ]
